name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        # https://hexdocs.pm/elixir/compatibility-and-deprecations.html
        # https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp
        elixir: ["1.5"]
        otp: ["20"]
        os: ["ubuntu-20.04"]
        include:
          - { elixir: "1.5", otp: "19", os: "ubuntu-18.04" }
          - { elixir: "1.5", otp: "18", os: "ubuntu-18.04" }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1.9.0
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}
    - run: mix compile --warnings-as-errors
    - run: mix test
